### ISSUE TITLE
Release v0.4.7.1 does not contain the compiled file grpc-labview.zip

### ISSUE THREAD

**Issue by jessaggie** [ni/grpc-labview#133]
The Release v0.4.7.1 does not contain the compiled file grpc-labview.zip. 
Adding the compiled version can speed up developer workflow for people still using Release v0.4.7.1.  Thanks!

**Comment by gregr-ni** [comment]
The tag for that release was misnamed. I corrected that but now the zip file shows up under [release assets](https://github.com/ni/grpc-labview/releases/tag/untagged-a17eb5f9bd93d75b6cb3) and not [under the tag](https://github.com/ni/grpc-labview/releases/tag/v0.4.7.1). The zip under the release is still has the origin moddate from when the release was first created so that it the file we want. The release is also now showing as a draft. I'm not sure if just hitting publish will make the zip visible to the tag. I'm waiting for clarification from those that know more about github workflows.

@ccifra @gaoruhao

**Comment by gaoruhao** [comment]
I cannot visit the [release assets](https://github.com/ni/grpc-labview/releases/tag/untagged-a17eb5f9bd93d75b6cb3) link. I guess the non-admin users do not have permissions to view a draft release.

**Comment by gregr-ni** [comment]
I published the draft release and I think the zip should now be visible.

**Comment by jessaggie** [comment]
Fantastic.  Its visible now. Going to go ahead and close the issue.
