### ISSUE TITLE
Oneof support

### ISSUE THREAD

**Issue by ccifra** [ni/grpc-labview#21]
Oneof is not currently support for reading for writing.  For writing we need to define a mechanism which defines which value is set . For reading we need a mechanism to indicate which value is set.

**Comment by navinsubramani** [comment]
I have provided my suggestion for the oneof APIs in LabVIEW, please feel free to add comments.

Currently (0.4) oneof generates all the data in the message field in LabVIEW like below,

**Example proto:**
![image](https://user-images.githubusercontent.com/17029551/145242553-f979549c-25df-47ad-b3a9-f1dd5fbb550d.png)

**Code Generated in LabVIEW (0.4):**
![image](https://user-images.githubusercontent.com/17029551/145242644-8390f5b7-1ded-4953-a7a3-8aae5f7ff297.png)
![image](https://user-images.githubusercontent.com/17029551/145242659-d56aa7b6-cef8-482e-8ee3-d90253fc7244.png)

**New suggestion:**
Instead of generating all the elements under oneof, can we create a reference to the oneof with the name of oneof from the proto file. For above example, the name of oneof is greeting. So, instead of creating elements like a,b in LabVIEW, we could create a ref for the greeting as shown below,

![image](https://user-images.githubusercontent.com/17029551/145243005-f74921ea-2c16-4691-8bf0-df5a0993a2f7.png)

the name of the element in LabVIEW can be something like "<oneof name>_oneof_id

**APIs to Read oneof:**

Now unbundling the message will provide the oneof ID. Developers will be provided with a API in LabVIEW gRPC support to "Get oneof element name" present in oneof. For example: from above example, if the value in oneof is of "a" string, then the API returns "a".

![image](https://user-images.githubusercontent.com/17029551/145243456-c7477c61-57bb-4694-a8c5-4ad1990b2f73.png)

**APIs to Write to oneof:**

To set the oneof value, developers will have a API like "Set oneof value" which will take in the "element name" and "value" to return a oneof id. This id can be set to the "set message" function.

![image](https://user-images.githubusercontent.com/17029551/145243963-b2771c67-7c9a-4b01-9b39-724359993731.png)

Note: The API definition can be changed from the above example.

**Comment by navinsubramani** [comment]
Here is a example of addressing the Oneof using LabVIEW classes. Please add your suggestion.

below is the proto file:

```proto
syntax = "proto3";

package helloworld;

// The greeting service definition.
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}


message Place {
  string location = 1;
}

message Person {
  string name = 1;
}

// The request message containing the user's name.
message HelloRequest {
  string text = 1;
  oneof instrument {
    Place place = 2;
    Person person = 3;
  }
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}
```

Here is the attached functional example:
[helloworld_oneof.zip](https://github.com/ni/grpc-labview/files/7990949/helloworld_oneof.zip)

Each oneof is created as a class:
- Contains basic get and set methods for each fields
- Contains a 'oneof" control that contains all its fields which is a class member
- Contains methods like 'create', g'oneof_name' and 'oneof_elements' to get more details about the oneof. Some of these can be inherited from a parent oneof if we want to take some default implementation to parent.

![image](https://user-images.githubusercontent.com/17029551/152262002-300a7beb-0c2f-47ca-ae01-92f994f2c921.png)

Messages that has oneof fields in them will be like,
![image](https://user-images.githubusercontent.com/17029551/152262226-71529ab4-3758-4a80-b977-22f1260ec690.png)

Scripting is bit complex, but it can be done under the "Set" and "Get" method for messages, like below,

Set method is as below,
![image](https://user-images.githubusercontent.com/17029551/152262299-6feb1c82-48fc-4965-be0a-3fbf0b4f8a23.png)

For Get Message, we need the C++ dll to say what element from the oneof has values,
![image](https://user-images.githubusercontent.com/17029551/152262385-9e1eba1d-d5c5-46d5-9fcc-4c6cf8fb586e.png)

No other changes in server side templates, apart from what is mentioned above.

Client Side template scripting is bit more work as the methods now will take object as input/output , and convert them into data internally.
![image](https://user-images.githubusercontent.com/17029551/152262502-910425d3-7a74-4b6c-bd6c-6cfdadd3b49f.png)


Please share the suggestions. cc. @ccifra

**Comment by navinsubramani** [comment]
This implementation might become complex when we have a oneof that contains a message which inturn contains a oneof and so on.

**Comment by ccifra** [comment]
This looks just about right.  For the set we will have to pass to C++ what field is actually set since it may not be obvious.  And for the get, like you mentioned, the C++ will have to return what was set.  I was thinking that we would just have one more element in the cluster which indicates what field is set (by protobuf ID?).

**Comment by jasonmreding** [comment]
For C#, something like this:

```
oneof result {
  google.rpc.Status error = 4;
  google.protobuf.Any response = 5;
}
```
would generate:

```CSHARP
    public enum ResultOneofCase {
      None = 0,
      Error = 4,
      Response = 5,
    }

    private ResultOneofCase resultCase_ = ResultOneofCase.None;

    public ResultOneofCase ResultCase {
      get { return resultCase_; }
    }
```
which would then get consumed in client code via a switch statement. Perhaps the same thing would make sense here with a case structure? Client code trying to figure out which field was set by comparing against a protobuf ID seems like it would be error prone and a readability nightmare.
