### ISSUE TITLE
Calling gRPC client API in VMWare machine will sometimes hang

### ISSUE THREAD

**Issue by wendisong** [ni/grpc-labview#320]
Hi,

Currently I am developing my code in VMWare machine, and I also use grpc as dependency. I found that if I try to call generated grpc client API for overnight test, then it will hang.
I attached my test code here.
[gRPC_Hang_Issue.zip](https://github.com/ni/grpc-labview/files/12844113/gRPC_Hang_Issue.zip)

### VMWare Machine
CPU: i7-6700 2C4T
Mem: 8GB
![image](https://github.com/ni/grpc-labview/assets/50438064/a0b8b5c4-0afa-4ce7-87df-617f9f2d6075)

### Steps to reproduce
1. Open attached project and then run the server/client example
![image](https://github.com/ni/grpc-labview/assets/50438064/7deef7ce-b108-4bd2-b0dc-493c2549b8c7)

2. When the test code is running, then swirch the windows focus to another app such as Task manager.
3. Then you will see the client example hang. Give focus back to LabVIEW will not fix this issue. The CPU usage of my virtual machine is ~50%, and never reach >70% during testing procedure.
![image](https://github.com/ni/grpc-labview/assets/50438064/afd0ce36-8fd9-4c4a-b88e-13a513fb0a50)

### Guess
This may be caused by CPU logic processor auto-assignment. My VMWare machine is not so powerful so it could reproduce this issue.

Any idea?

**Comment by wendisong** [comment]
@yijueli, FYI

**Comment by AndrewHeim** [comment]
I was experiencing something like this too, so I investigated.

**Situation:**
Very simple example using local loopback, wrap client in a For Loop for tens of thousands of iterations, reusing client grpc session between iterations.  Running in Windows 10 on a bare metal machine that isn't as resource constrained as your VM.   gRPC Library, Servicer, and Templates all version 1.0.1.1.

I'm seeing it hang occasionally, though not on the same iteration.  The client call appears to ignore the timeout indefinitely, but it is a hang - since closing the (apparently still responsive) server leaves the client unchanged, still hung.


**Possible solution:**
Race condition.  Here's the details:

For me, the hang is in Client Unary Call.vim.  It's a vim, so it's inlined and I can't easily get debugging in there.  But I do see that there's a Wait for Occurrence in there.  It looks like the Occurrence fires after the reply comes in, so LV can come pick up the respnse.  My guess is it's a race condition and on a fast machine, the occurrence is firing in the DLL before LabVIEW has resumed its thread and is fully waiting on that occurence.

To test this, I put a 1ms wait in my server call.  I had already been testing round trip timing, and seeing I was getting an average time well below a millisecond round trip - about 142 us.  I figured if a race could happen, it would most likely be seen on local loopback testing where there's minimal latency.  Windows thread swapping can go slower than that (my experience is USB can vary 30 ms from iteration to iteration sometimes), so it's possible.

After putting the 1ms wait in my server call, I ran for several times the average number of iterations and there was no hang.  Removing it again, I got one right away.

To me that's a pretty clear call - this will be stable over a real life network, but is unstable on local loopback interfaces where latencies are low.  That explains the testing I've seen on presentations from Chris Cifra - it's unstable over a real network.  Still a problem that needs to be solved, but of a different sort.

**Comment by AndrewHeim** [comment]
Solution is related to #193 .  I don't have a LV 2019 environment right now, but this fix works locally for me.

**Comment by wendisong** [comment]
Will this fix be invloved in next gRPC release?

**Comment by twaltersp** [comment]
Adding a use case to help with prioritization for a fix.  We are seeing a hang when doing gRPC client calls to a gRPC server on the same LinuxRT machine.  gRPC is our exposed API for monitoring and managing the application and some of the orchestration needs to run directly on the RT system.  
[
](https://github.com/ni/adas-replay-hil-internal/discussions/1020)

**Comment by twaltersp** [comment]
@yash-ni @wendisong @AndrewHeim 

I just ran a 17 hour test using the new .so with the fix.  Over 18M calls directly on the RT system and no issues (previously I would see failures in roughly 10 minutes).  Wanted to drop a quick note and thank you for the work to fix the issue!  Please pass on to anyone else that worked to root cause and fix.  

The LV gRPC tools are super valuable, keep up the good work!

**Comment by wendisong** [comment]
Since the isue is fixed and validated, then I will close this issue. Thanks for fixing the issue.
