### ISSUE TITLE
New Modular Service Template

### ISSUE THREAD

**Issue by navinsubramani** [ni/grpc-labview#42]
Some of the current limitations of the previous templates are,
1. Template combines RPC messages and RPC methods into a single class (but proto can have many services per message)
2. The server creation and close is coupled with the service methods and messages functions
3. Only one service can run on a port number

The requirement for the new template is to,
1. Modularize RPC messages, RPC service(s) and gRPC server/servicer functionality
2. Enable user to add more than one service class to the library and run them on same port
3. Create API and parent classes and abstract the common functionality out of the specific library

Some design note:
![image](https://user-images.githubusercontent.com/17029551/142708029-1de8abef-862b-4cfb-83e4-65ba201aaa99.png)

![image](https://user-images.githubusercontent.com/17029551/142708061-2f6e2e55-0917-4db7-b08e-a24e43dccea8.png)

![image](https://user-images.githubusercontent.com/17029551/142708071-38415103-36e8-4ab7-8c20-513de90de17d.png)

![image](https://user-images.githubusercontent.com/17029551/142708082-46452d5d-c979-402d-aba1-d85e6a2effec.png)

![image](https://user-images.githubusercontent.com/17029551/142708098-ba8254ce-145d-463e-b33c-b85eb0ca018f.png)

**Comment by chrisb2244** [comment]
Obviously I'm new to all of this, so feel free to ignore these thoughts, but here they are anyway:

- Most LabVIEW libraries I've seen don't use the "i\<Feature\>" naming, even for interface-like/abstract-ish classes. Perhaps a name like "gRPC Service" (or "RPC Service"?) would be more "LabVIEW-like"?
- Your proto file has "SignalGeneratorService2" (no space), whilst the class became "SignalGeneratorService 2.lvclass". Was this just an accident in the example (I guess from the comment on #17 that this was created manually and not scripted?) or is this an intentional naming choice?

Otherwise seems very nice to me. Will download the code in the PR and look at implementation too, but as I said please don't think too much of my thoughts!

**Comment by navinsubramani** [comment]
@chrisb2244  Since, this is hand created example, I created the proto and code separately. You are right #2 is a mistake. The name of the LabVIEW class will be the same as the service defined in the proto.

#1 good thought. I started that as an interface class but I don't think it's an interface. We could change that something like ServiceBase, as it has some base implementation in them. Good point!
