### ISSUE TITLE
Operate grpc-labview - DLL missing

### ISSUE THREAD

**Issue by UvQtcYZJuD7J5VW7** [ni/grpc-labview#63]
Hi,

Where can I find the DLLs? Are they generated by gRPC Code Generator or do I have to download them (not found in GitHub) ?
![Capture](https://user-images.githubusercontent.com/90563484/150165549-d07f4095-e6d8-4124-adcd-3d76745ff2ff.JPG)
![Capture](https://user-images.githubusercontent.com/90563484/150165620-bb498755-d896-4d1b-9e76-f71a6f327b6e.JPG)

I get error code 7 when I execute _Run Service.vi_.

Regards

**Comment by navinsubramani** [comment]
Hello - Are you using the released package? because the packages have the other case enabled and this disabled.
![image](https://user-images.githubusercontent.com/17029551/150166585-c0d3f556-a012-4b2a-9822-1822620dcc60.png)

If not, please enable the other case.

If you are trying to contribute by using the source code - you can either build the dlls using the build procedure from readme or use the dlls from 'vi.lib\gRPC\LabVIEW gRPC Library\Libraries'

**Comment by UvQtcYZJuD7J5VW7** [comment]
I use released package. To be sure, I download again all master-branch files and I try again.
I create a new project and I run gRPC Code Generator. All work fine but _Get Server DLL Path.vi_ has enabled constant.
![Capture](https://user-images.githubusercontent.com/90563484/150168474-0afc93cc-996f-4966-8afd-6d343b9eafe5.JPG)

Now I know, I change enabled-disabled case and it seems to work.

Before contributing, I try to understand your project and operate it.

Thanks

**Comment by navinsubramani** [comment]
Hi - Actually this is a bug in 0.4.6 release which is not in 0.4.5. But this is fixed now. If you download the latest version now, this issue should have been fixed.
